@startuml
left header
<font color=000 size=18><b>Package:</b> Student

<font color=000 size=16><b>ID:</b> SC-2
<font color=000 size=16><b>Назва:</b> Подання заяв.
<font color=000 size=16><b>Учасники:</b> Студент, Система.
<font color=000 size=16><b>Передумови:</b> Аутентифікація користувача Студент у системі.
<font color=000 size=16><b>Результат:</b> Студент подав заяву на вступ до обраного ВНЗ на обрану спеціальність.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> ES_01: Ще не розпочався період подачі заяв
<font color=000 size=16> ES_02: Така спеціальність не є в наявності
<font color=000 size=16> ES_03: Запит не відбувся успішно через технічні недоліки

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Студент|
start
: Студент завантажує сторінку для пошуку необхідної спеціальності;

|Система|
: Система надає Студентові форму, де вказані
   варіативні drop-down списки для вводу даних:
   ВНЗ, факультет, номер спеціальності;

|Студент|
: Студент обирає необхідні дані;

|Система|
: Система перевіряє можливість подачі заяви на вказану спеціальність;
note right #aaffaa

<font color=red><b> Можливо ES_01.
<font color=red><b> Можливо ES_02.

end note

: Система фіксує запит у БД та повертає Студенту
   повідомлення про успішність подачі заяви;
note right #aaffaa

<font color=red><b> Можливо ES_03.

end note

|Студент|

: Студент отримує повідомлення про успішно відправлену заяву;

stop;

right footer
Система подавання заяв у ВНЗ на основі балів ЗНО. Модель прецедентів.
НТУУ "КПІ" ім. Ігоря Сікорського
Київ, 2020.
end footer

@enduml
