@startuml
left header
<font color=000 size=18><b>Package:</b> Student

<font color=000 size=16><b>ID:</b> LOC
<font color=000 size=16><b>Назва:</b> Вихід з облікового запису.
<font color=000 size=16><b>Учасники:</b> Студент, Система.
<font color=000 size=16><b>Передумови:</b> Аутентифікація користувача Студент у системі.
<font color=000 size=16><b>Результат:</b> Студент вийшов із системи, набувши роль Глядача.
'<font color=000 size=16><b>Виключні ситуації:</b>
'<font color=000 size=16> ES_04: Немає поданих заяв

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Студент|
start
: Студент завантажує персональну сторінку;

|Система|
: Система надає Студентові сторінку для керування профілем;

|Студент|
: Студент надає запит "Вийти із системи";

|Система|

: Система отримує запит, виконує процедуру для
   припинення аутентифікації користувача у системі;

|Студент|

: Студент потрапляє на сайт із роллю Глядача;

stop;

right footer
Система подавання заяв у ВНЗ на основі балів ЗНО. Модель прецедентів.
НТУУ "КПІ" ім. Ігоря Сікорського
Київ, 2020.
end footer

@enduml
