@startuml
left header
<font color=000 size=18><b>Package:</b> Student

<font color=000 size=16><b>ID:</b> SC-1
<font color=000 size=16><b>Назва:</b> Внесення даних ЗНО.
<font color=000 size=16><b>Учасники:</b> Студент, Система.
<font color=000 size=16><b>Передумови:</b> Аутентифікація користувача Студент у системі.
<font color=000 size=16><b>Результат:</b> Студент надав необхідні дані про себе.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> ES_00: Надано не всі необхідні дані

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Студент|
start
: Студент завантажує сторінку для пошуку необхідної спеціальності;

|Система|
: Система надає Студентові форму для заповнення
   даних про себе: ПІБ, копії документів, бали ЗНО;

|Студент|
: Студент вводить ці дані;

note right #aaffaa

<font color=red><b> Можливо ES_00.

end note

|Система|
: Система зберігає дані в базі,
   відправляє повідомлення про успішність операції;

|Студент|

: Студент отримує повідомлення;

stop;

right footer
Система подавання заяв у ВНЗ на основі балів ЗНО. Модель прецедентів.
НТУУ "КПІ" ім. Ігоря Сікорського
Київ, 2020.
end footer

@enduml
