= База Даних абітурієнтів ЗНО : Запити зацікавлених осіб
Долгова Єлизавета, Рекечинський Дмитро, Цасюк Ілля
Версія 1.0.2, 20 жовтня 2020 року
:toc: macro
:toc-title: Зміст
:sectnums:
:chapter-label:

<<<

[preface]
.Список змін
|===
|Дата |Версія |Опис |Автори

|21.09.2020
|1.0
|Створення документа
|Долгова Єлизавета, Рекечинський Дмитро, Цасюк Ілля

|12.10.2020
|1.0.1
|Правки у документ
|Рекечинський Дмитро

|20.10.2020
|1.0.2
|Додано інформацію про користувачів, схеми для наочності
|Долгова Єлизавета, Рекечинський Дмитро, Цасюк Ілля
|===

<<<

== 1. Вступ
У цьому документі описуються засоби зацікавлених осіб для
БД абітурієнтів ЗНО. Зацікавленими особами
є майбутні користувачі застосунку та його адміністрація.

=== 1.1. Мета
Метою документу є визначення основних вимог до функції, що виконує
застосунок, а також правил та обмежень, що стосуються застосунку.

=== 1.2. Контекст
Перелік вимог, що описані у цьому документі, є основою технічного
завдання на розробку бази даних абітурієнтів ЗНО.

=== 1.3. Список скорочень
БД - База даних
ЗНО - зовнішнє незалежне оцінювання
КБ - конкурсний бал

== 2. Короткий огляд продукту
БД для абітурієнтів являтиме собою платформу для внесення заяв на вступ в
університет. Абітурієнти зможуть вносити дані своїх ЗНО, а також бажаних
ВИШів для вступу. Користувачі зможуть використовувати цей продукт через
веб-інтерфейс.

== 3. Характеристика ділових процесів

=== 3.1 Призначення системи
БД для абітурієнтів призначена для надання можливості централізованого збору
та обробки заяв від абітурієнтів.

=== 3.2 Типи користувачів
У цьому засобі розглядаються 3 типи користувачів:

* Глядач (Viewer)
* Студент (Student)
* Адміністратор (Admin)

==== 3.2.1 Глядач
Цей тип користувача має право лише на перегляд поданих заяв.
Але він може зареєструватись та аутентифікуватись як
Студент, або аутентифікуватись як Адміністратор.

==== 3.2.2 Студент
Цей тип успадкований від типу Глядач та має додаткові права, а саме:

* Вихід із системи
* Внесення даних ЗНО
* Подання заяв
* Видалення заяв

Разом з тим, є вимоги для забезпечення надійності даних:

* Бути зареєстрованим у системі
* Надавати достовірну інформацію про себе та результати ЗНО

Цей тип представляє абітурієнт ЗНО.

==== 3.2.3 Адміністратор
Цей тип користувача відповідає за безперебійну роботу БД, а також за
коректність даних. Адміністратор успадкований від типу Глядач.

Крім цього, йому надані такі права:

* Вихід із системи
* Редагування даних користувача Студент
* Видалення заяв користувача Студент
* Видалення облікового запису користувача Студент

Разом з тим, Адміністратор не може додавати заяви для того, щоб
запобігти шахрайству.

=== 3.2 Взаємодія з користувачами
Взаємодія з користувачами буде проходити за допомогою веб-застосунку.

=== 3.3 Характеристика бізнес-процесу
Управління системою буде виконуватись за допомогою відокремленого розділу
веб-застосунку та за допомогою спеціальної команди адміністрування в складі
адміністраторів.

== 4. Функціональність.

=== 4.1. Функція реєстрації
Користувачі зможуть зареєструвати свій робочий кабінет для внесення даних та
відстежування змін.

=== 4.2. Функція внесення даних ЗНО.
Для реєстрації абітурієнти матимуть можливість внести результати своїх ЗНО
та отримати автоматичний розрахунок КБ.

=== 4.3. Функція подання заяв.
Зареєстровані користувачі можуть подати заяви на обрані спеціальності.

=== 4.4. Функція перегляду поданих заяв.
Кожен користувач може переглядати подані заяви.

=== 4.5. Функція керування заявами.
Зареєстровані користувачі можуть видаляти власні подані заяви, але додавати
нові після видалення не зможуть.

=== 4.6. Функція модерації.
Адміністратори матимуть можливість відстежувати коректність роботи бази
даних, а також слідкувати за безпечністю.

== 5. Доступність.
=== 5.1. Локалізація.
Інтерфейс веб-застосунку повинен бути локалізованим на українську мову.

=== 5.2. Програмні платформи.
Веб-застосунок повинен коректно показуватися в усіх веб-браузерах останніх
версій.

=== 5.3. Інтерфейс.
Інтерфейс веб-застосунку повинен бути адаптований для роботи людей з різними
вадами здоров'я.

== 6. Відмовостійкість.
Система повинна мати високий рівень відмовостійкості. Він буде забезпечуватися
резервним копіюванням даних, дублюванням баз даних, серверів тощо.

== 7. Захищеність.
Дані користувачів системи повинні буди надійно захищенні від сторонніх осіб
шляхом шифрування та організації аутентифікованого доступу.
