@startuml

title
<font size=18 color=black>Система подавання заяв у ВНЗ на основі балів ЗНО
<font size=16 color=black>Діаграма прецедентів
end title


' Set actors
actor "Глядач" as Viewer
actor "Студент" as Student
actor "Адміністратор" as Admin

' Use cases

' Use case, general for everyone (General Use Case)
usecase "<b>GUC</b>\nПерегляд поданих заяв" as GUC

' Registration use case (RUC)
usecase "<b>RUC</b>\nРеєстрація у системі" as RUC

' Student use cases (SC)
usecase "<b>SC-1</b>\nВнесення даних ЗНО" as SC1
usecase "<b>SC-2</b>\nПодання заяв" as SC2
usecase "<b>SC-3</b>\nВидалення заяв" as SC3

' Admin use cases
usecase "<b>AC-1</b>\nРедагування даних користувача Студент" as AC1
usecase "<b>AC-2</b>\nВидалення записів користувача Студент" as AC2

' Derivation links
Student -u-|> Viewer
Admin -u-|> Viewer

' Use case linking
Viewer -u-> GUC

Student -u-> RUC
Admin -u-> RUC

Student -l-> SC1
Student -d-> SC2
Student -r-> SC3

Admin -d-> AC1
Admin -r-> AC2

right footer
Система подавання заяв у ВНЗ на основі балів ЗНО. Модель прецедентів.
НТУУ "КПІ" ім. Ігоря Сікорського
Київ, 2020.
end footer

@enduml