@startuml
left header
<font color=000 size=18><b>Package:</b> General

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Авторизація.
<font color=000 size=16><b>Учасники:</b> Глядач, Система.
<font color=000 size=16><b>Передумови:</b> Глядач.
<font color=000 size=16><b>Результат:</b> Користувач авторизувався в системі.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EU_00: Введеного акаунту не існує
<font color=000 size=16> EU_01: Введений пароль від акаунту не дійсний 

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Глядач|
start
: Глядач натискає кнопку логування;

|Система|
: Система надає користувачу форму, де вказані
   поля для вводу імені акаунту та пароля від нього;

|Глядач|
: Користувач вводить дані для акаунту;   

: Користувач натискає кнопку "Ввійти";

|Система|
: Система перевіряє наявність введеного акаунту;
note right #aaffaa

<font color=red><b> Можливо EU_00.

end note

: Система перевіряє правильність введеного паролю від акаунту;

note right #aaffaa

<font color=red><b> Можливо EU_01.

end note

: Система надає користувачу доступ до його акаунту;

|Глядач|

: Користувач входить в свій обліковий запис;

stop;

right footer


Система подавання заяв у ВНЗ на основі балів ЗНО. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
