@startuml
left header
<font color=000 size=18><b>Package:</b> General

<font color=000 size=16><b>ID:</b> RUC
<font color=000 size=16><b>Назва:</b> Реєстрація у системі
<font color=000 size=16><b>Учасники:</b> Глядач, Система.
<font color=000 size=16><b>Передумови:</b> Неавторизований в системі користувач.
<font color=000 size=16><b>Результат:</b> Користувач реєструється в системі
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16>EA_00: Введені хибні дані

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Глядач|
start
: Глядач натискає кнопку "Реєстрація";

|Система|
: Система надає користувачу форму для реєстрації;

|Глядач|
: Користувач вводить свої дані;   

: Користувач натискає кнопку "Зареєструватися";

|Система|
: Система перевіряє правильність вводу даних;

note right #aaffaa

<font color=red><b> Можливо EA_00.

end note

: Система зберігає дані користувача;

: Система надає користувачу доступ до аккаунту;

|Глядач|

: Користувач використовує свій аккаунт;

stop;

right footer


Система подавання заяв у ВНЗ на основі балів ЗНО. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
