
@startuml
left header
<font color=000 size=18><b>Package:</b> General

<font color=000 size=16><b>ID:</b> GUC
<font color=000 size=16><b>Назва:</b> Перегляд поданих заяв
<font color=000 size=16><b>Учасники:</b> Глядач, Система.
<font color=000 size=16><b>Передумови:</b> Неавторизований в системі користувач.
<font color=000 size=16><b>Результат:</b> Користувач переглядає список поданих заяв.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EG_00: Ще не розпочався період подачі заяв
<font color=000 size=16> EG_01: Введеного інституту не існує
<font color=000 size=16> EG_02: Введеного факультету не існує
<font color=000 size=16> EG_03: Введеної спеціальності не існує
<font color=000 size=16> EG_04: Заяви на обрану спеціальність ще не були подані

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Глядач|
start
: Глядач натискає кнопку пошуку спеціальності;

|Система|
: Система надає користувачу форму, де вказане
   поле для вводу імені університету, факультету та спеціальності;

|Глядач|
: Користувач вводить ім'я університету, факультету та спеціальності;   

: Користувач натискає кнопку "Пошук";

|Система|
: Система перевіряє наявність університету, факультету та спеціальності із вказаним ім'ям;
: Система перевіряє наявність заяв на подану спеціальність;

note right #aaffaa

<font color=red><b> Можливо EU_01.
<font color=red><b> Можливо EU_02.
<font color=red><b> Можливо EU_03.

end note

note right #aaffaa

<font color=red><b> Можливо EU_00.
<font color=red><b> Можливо EU_04.
end note


: Система надає розклад групи користувачу;

|Глядач|

: Користувач переглядає список;

stop;

right footer


Система подавання заяв у ВНЗ на основі балів ЗНО. Модель прецендентів.
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
