@startuml
left header
<font color=000 size=18><b>Package:</b> General

<font color=000 size=16><b>ID:</b> GUC
<font color=000 size=16><b>Назва:</b> Перегляд поданих заяв.
<font color=000 size=16><b>Учасники:</b> Глядач (або користувач з вищими правами, далі - Глядач), Система.
<font color=000 size=16><b>Передумови:</b> жодні.
<font color=000 size=16><b>Результат:</b> Глядач переглядає список поданих заяв.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EG_00: Ще не розпочався період подачі заяв
<font color=000 size=16> EG_01: Заяви на обрану спеціальність ще не були подані

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Глядач|
start
: Глядач завантажує сторінку для пошуку заяв;

|Система|
: Система надає Глядачу форму, де вказані
   варіативні drop-down списки для вводу даних:
   ВНЗ, факультет, номер спеціальності;

|Глядач|
: Глядач обирає необхідні дані;

|Система|
: Система перевіряє наявність заяв до вказаної спеціальності;
note right #aaffaa

<font color=red><b> Можливо EG_00.
<font color=red><b> Можливо EG_01.

end note

: Система надає список заяв користувачу;

|Глядач|

: Глядач переглядає список заяв;

stop;

right footer
Система подавання заяв у ВНЗ на основі балів ЗНО. Модель прецедентів.
НТУУ "КПІ" ім. Ігоря Сікорського
Київ, 2020.
end footer

@enduml
