= База Даних абітурієнтів ЗНО : Запити зацікавлених осіб
Долгова Єлизавета, Рекечинський Дмитро, Цасюк Ілля
Версія 1.0, 21 вересня 2020 року
:toc: macro
:toc-title: Зміст
:sectnums:
:chapter-label:

<<<

[preface]
.Список змін
|===
|Дата |Версія |Опис |Автори

|21.09.2020
|1.0
|Створення документа
|Долгова Єлизавета, Рекечинський Дмитро, Цасюк Ілля
|===

<<<

== Вступ
У цьому документі описуються засоби зацікавлених осіб для
бази даних абітурієнтів ЗНО. Зацікавленими особами
є майбутні користувачі застосунку та його адміністрація.

=== Мета
Метою документу є визначення основних вимог до функції, що виконує
застосунок, а також правил та обмежень, що стосуються застосунку.

=== Контекст
Перелік вимог, що описані у цьому документі, є основою технічного
завдання на розробку бази даних абітурієнтів ЗНО.

== Короткий огляд продукту
БД для абітурієнтів являтиме собою платформу для внесення заяв на вступ в університет. Абітурієнти зможуть вносити дані своїх ЗНО, а також бажаних ВУЗів для вступу.

== Характеристика ділових процесів

=== Призначення системи
БД для абітурієнтів призначена для надання можливості централізованого збору та обробки заяв від абітурієнтів.

=== Взаємодія з користувачами
Взаємодія з користувачами буде проходити за допомогою веб-застосунку.

=== Характеристика бізнес-процесу
Управління системою буде виконуватись за допомогою відокремленого розділу
веб-застосунку та за допомогою спеціальної команди адміністрування в складі
адміністраторів.

== Функціональність.

=== Функція внесення даних ЗНО.
Для реєстрації абітурієнти матимуть можливість внести результати своїх ЗНО та отримати автоматичний розрахунок конкурсного балу.

=== Функція подання заяв.
Зареєстровані користувачі можуть подати заяви на обрані спеціальності.

=== Функції пов'язані з каналами заявами.
Зареєстровані користувачі можуть видаляти подані заяви, але додавати нові після видалення не зможуть.

=== Функція модерації.
Адміністратори матимуть можливість відстежувати коректність роботи бази даних, а також слідкувати за безпечністю.

== Доступність.
=== Локалізація.
Інтерфейс веб-застосунку повинен бути локалізованим на українську мову.

=== Програмні платформи.
Веб-застосунок повинен коректно показуватися в усіх веб-браузерах останніх версій.

=== Інтерфейс.
Інтерфейс веб-застосунку повинен бути адаптований для роботи людей з різними вадами здоров'я.

== Відмовостійкість.
Система повинна мати високий рівень відмовостійкості. Він буде забезпечуватися резервним
копіюванням даних, дублюванням баз даних, серверів тощо.

== Захищеність.
Дані користувачів системи повинні буди надійно захищенні від сторонніх осіб шляхом
шифрування та організації аутентифікованого доступу.
